# Change these first
owner: kiro # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: KiroFyzu Website
    url: https://kiro.my.id/
  - name: KiPanel | Pterodatcy
    url: https://panel.kiro.my.id/
  - name: KiBOT | Bot WhatsApp
    url: https://app.kiro.my.id
  - name: KiForm | Forum by Diqus
    url: https://kiform.kiro.my.id/
  - name: KiTok | Downloader Tiktok
    url: https://kitok.kiro.my.id/
  - name: KiAPI (Coming Soon)
    url: https://kiapi.kiro.my.id/
  - name: KiHOST | Hosting File
    url: https://kihost.kiro.my.id/

status-website:

  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Kiro Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: Instagram
      href: https://instagram.com/callme_kiro
  links:
    - rel: stylesheet
      href: https://phoenixsheppy.github.io/css/upptime/DarkBlue.css
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
