# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: theATL.social Main Site
    url: https://theatl.social/about
  - name: theATL.social API Feed
    url: https://theatl.social/api/v1/timelines/public?local=true&only_media=false
  - name: about.theATL.social
    url: https://about.theatl.social

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.theATL.social
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**status.theATL.social** provides status uptime/downtime updates for theATL.social"
  introMessage: "This site monitors the status of the Mastodon instance's main page, API, and about page. For questions or comments, please refer to the incident report links or email [admin@theatl.social](mailto:admin@theatl.social)"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
